In [3]:
print("Hello World")

Hello World

In [4]:
import pandas as pd

In [6]:
validation_dataset = pd.read_csv("MGdataset_P2_validation.csv")

In [7]:
validation_dataset

                                                      O_order;O_code;O_dlots;O_Nlot;O_aval;O_daval;O_year_p;O_countryp_code;O_finstr;R_bids;O_dnegotiated;O_scope;O_catpro;E_GDP_1;E_DTF_1;E_distance
600;157602;1;3;1400;1;2018;TK;IPA;;0;1;3;1200  876;73                                            26;2516
601;157603;1;2;17000;1;2018;TK;IPA;;1;0;4;1200 876;73                                            26;3105
602;157604;0;1;8000;1;2018;LB;ENI;;0;0;3;43    95;71                                             96;3136
603;157605;1;2;8000;1;2018;LB;ENI;;1;0;3;43    95;71                                             96;3136
604;157606;1;2;4000;1;2018;BA;IPA;;0;0;2;19    2;69                                              76;1307
605;157607;1;3;2500;1;2018;MK;IPA;;0;1;1;11    02;74                                             43;1629
606;157608;1;4;2000;1;2018;MK;IPA;;0;0;2;11    02;74                                             43;1629
607;157609;0;1;400;1;2018;XK;EULEX;;0;1;1;7    35;67                                              7;1563
608;157610;1;1;400;1;2018;XK;EULEX;;0;1;1;7    35;67                                              7;1563
609;157611;0;1;5000;1;2018;TK;IPA;;0;0;2;1200  876;73                                            26;2516
610;157612;1;4;3000;1;2018;TK;IPA;;0;0;3;1200  876;73                                            26;2520
611;157613;1;2;2500;1;2018;LB;ENI;;0;0;3;43    95;71                                             96;3136
612;157614;1;4;1000;1;2018;LB;ENI;;0;0;3;43    95;71                                             96;3136
613;157615;1;2;4000;1;2018;MK;IPA;;0;0;2;11    02;74                                             43;1629
614;157616;1;5;1500;1;2018;MK;IPA;;0;0;4;11    02;74                                             43;1629
615;157617;0;1;3500;1;2018;MK;IPA;;0;1;2;11    02;74                                             43;1629
616;157618;1;1;21200;1;2018;TN;ENI;;1;0;1;48   9;82                                              17;1628
617;157619;0;1;62000;1;2018;SB;IPA;;0;0;3;42   22;72                                             13;1370
618;157620;1;1;9317;1;2018;SB;IPA;;0;0;4;42    22;72                                             13;1370
619;157621;0;1;2000;1;2018;XK;EULEX;;0;1;3;7   35;67                                              7;1563

In [10]:
raw_data = pd.read_csv("MGdataset_P2.csv", on_bad_lines='skip')
#is this right?

In [11]:
raw_data

                                                                                      O_order;O_code;O_dlots;O_Nlot;O_aval;O_daval;O_year_p;O_countryp_code;O_finstr;R_bids;R_dbids;O_dnegotiated;O_scope;E_Pref;R_pcost;E_indice;O_catpro;E_GDP_1;E_DTF_1;E_distance;viable
119;131769;1;1;50000;1;2015;TK;IPA;1;1;0;0;3333333 33;2989000;0 8967;3;1025 467;72                                             83;2477;0
121;133560;1;1;40000;1;2015;TK;IPA;1;1;0;0;2666666 67;2749000;1 0309;3;1025 467;72                                             83;2995;0
125;135520;1;2;750;1;2015;SB;IPA;1;1;0;0;50000;... 7815;3;39    882;72      48;1370;0                                                NaN
126;135612;1;2;2500;1;2017;TK;IPA;1;1;1;0;166666   67;153580;0  9215;3;1122 512;73                                             26;2975;0
130;135853;1;2;18581;1;2014;LB;ENI;1;1;0;0;1238733 33;1217912;0 9832;3;40   91;71                                              87;3136;0
...                                                                                                                                  ...
479;138568;1;1;3500;1;2017;BA;IPA;7;1;0;0;233333   33;278763;1  1947;2;18   93;69                                              76;1307;1
482;134936;1;6;2500;1;2015;TK;IPA;8;1;0;0;166666   67;227828;1  367;3;1025  467;72                                             83;3018;1
500;137249;1;2;1000;1;2015;JO;ENI;;1;0;0;66666     67;54041;0   8106;2;29   501;78                                              2;3324;1
508;138256;1;2;6000;1;2016;ME;IPA;;1;0;0;400000... 45;2;4       529;79      37;1466;1                                                NaN
509;138256;1;3;2000;1;2016;ME;IPA;;1;0;0;133333    33;196449;1  4734;2;4    529;79                                             37;1466;1

[347 rows x 1 columns]

In [ ]:
# this is a test